name: pedometer
description: Pedometer

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sensors_plus: ^1.4.0
  syncfusion_flutter_charts: ^20.3.47
  scidart: ^0.0.2-dev.12
  fmin: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
